version: '3.8'
services:
  elasticsearch:
    image: 'elasticsearch:7.17.1'
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - '9200:9200'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=cortex
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - '/opt/cortex/vol/elasticsearch/data:/usr/share/elasticsearch/data'
      - '/opt/cortex/vol/elasticsearch/logs:/usr/share/elasticsearch/logs'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - conf_es:/usr/share/elasticsearch/config

  cortex:
    container_name: cortex
    restart: unless-stopped
    build: ./
    environment:
      - 'JOB_DIRECTORY=/opt/cortex/vol/cortex/jobs'
    volumes:
      - '/opt/cortex/vol/cortex/conf/application.conf:/etc/cortex/application.conf'
      - '/opt/cortex/vol/cortex/jobs:/opt/cortex/vol/cortex/jobs'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - analyzer_cortex:/opt/Cortex-Analyzers
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - '0.0.0.0:9001:9001'

volumes:
  conf_es:
    driver_opts:
      type: none
      device: /opt/cortex/vol/elasticsearch/conf
      o: bind
  analyzer_cortex:
    driver_opts:
      type: none
      device: /opt/cortex/vol/cortex/cortex-analyzers
      o: bind
